import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { Pet, PetFormData } from '../models/pet.model';

@Injectable({
  providedIn: 'root'
})
export class PetService {
  private apiUrl = 'http://localhost:18080/api';

  constructor(private http: HttpClient) { }

  getAllPets(): Observable<Pet[]> {
    return this.http.get<Pet[]>(`${this.apiUrl}/pets`).pipe(
      catchError(() => of(this.getMockPets()))
    );
  }

  getPetById(id: number): Observable<Pet | null> {
    return this.http.get<Pet>(`${this.apiUrl}/pets/${id}`).pipe(
      catchError(() => {
        const mockPets = this.getMockPets();
        return of(mockPets.find(pet => pet.id === id) || null);
      })
    );
  }

  addPet(petData: PetFormData): Observable<Pet> {
    return this.http.post<Pet>(`${this.apiUrl}/add-pet`, petData);
  }

  updatePet(id: number, petData: PetFormData): Observable<Pet> {
    return this.http.put<Pet>(`${this.apiUrl}/update-pet/${id}`, petData);
  }

  deletePet(id: number): Observable<void> {
    return this.http.delete<void>(`${this.apiUrl}/delete-pet/${id}`);
  }

  private getMockPets(): Pet[] {
    return [
      {
        id: 1,
        name: "Max",
        breed: "Golden Retriever",
        age: 3,
        sex: "Male",
        size: "Large",
        color: "Golden",
        weight: 30.5,
        imageUrl: "assets/portraits/Max.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: false,
        medicalNotes: "N/A",
        temperament: "Friendly",
        houseTrained: true,
        adoptionFee: 50.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-10-20",
        description: "Found near park",
        trainingLevel: "Leash trained",
        contactInfo: "shelter@example.com"
      },
      {
        id: 2,
        name: "Bella",
        breed: "Pomeranian",
        age: 2,
        sex: "Female",
        size: "Small",
        color: "Golden",
        weight: 3.5,
        imageUrl: "assets/portraits/Bella.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: false,
        medicalNotes: "N/A",
        temperament: "Friendly",
        houseTrained: true,
        adoptionFee: 50.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-20",
        description: "Found near park",
        trainingLevel: "Not leash trained",
        contactInfo: "shelter@example.com"
      },
      {
        id: 3,
        name: "Rocky",
        breed: "German Shepherd",
        age: 4,
        sex: "Male",
        size: "Large",
        color: "Dark & Brown",
        weight: 50.0,
        imageUrl: "assets/portraits/Rocky.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: true,
        medicalNotes: "N/A",
        temperament: "Aggressive",
        houseTrained: true,
        adoptionFee: 50.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-12-20",
        description: "Found abandoned",
        trainingLevel: "Leash trained",
        contactInfo: "shelter@example.com"
      },
      {
        id: 4,
        name: "Luna",
        breed: "Siamese",
        age: 2,
        sex: "Female",
        size: "Small",
        color: "Cream & Brown",
        weight: 5.0,
        imageUrl: "assets/portraits/Luna.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: true,
        medicalNotes: "N/A",
        temperament: "Calm",
        houseTrained: true,
        adoptionFee: 40.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-10",
        description: "Rescued from street",
        trainingLevel: "Indoor trained",
        contactInfo: "shelter@example.com"
      },
      {
        id: 5,
        name: "Polly",
        breed: "African Grey",
        age: 3,
        sex: "Female",
        size: "Medium",
        color: "Grey",
        weight: 0.9,
        imageUrl: "assets/portraits/Polly.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: false,
        medicalNotes: "Talks few words",
        temperament: "Playful",
        houseTrained: true,
        adoptionFee: 100.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-05",
        description: "Rescued from owner",
        trainingLevel: "Basic tricks",
        contactInfo: "shelter@example.com"
      },
      {
        id: 6,
        name: "Milo",
        breed: "Mixed Domestic",
        age: 2,
        sex: "Male",
        size: "Medium",
        color: "White",
        weight: 5.2,
        imageUrl: "assets/portraits/Milo.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: true,
        medicalNotes: "N/A",
        temperament: "Gentle",
        houseTrained: true,
        adoptionFee: 45.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-15",
        description: "Rescued from market side alley",
        trainingLevel: "Indoor trained",
        contactInfo: "shelter@example.com"
      },
      {
        id: 7,
        name: "Sky",
        breed: "Cockatiel",
        age: 1,
        sex: "Male",
        size: "Large",
        color: "Grey & Yellow",
        weight: 0.1,
        imageUrl: "assets/portraits/Sky.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: false,
        neuteredSpayed: false,
        medicalNotes: "N/A",
        temperament: "Playful",
        houseTrained: false,
        adoptionFee: 70.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-08",
        description: "Owner surrendered due to relocation",
        trainingLevel: "Basic sound mimicry",
        contactInfo: "shelter@example.com"
      },
      {
        id: 8,
        name: "Lily",
        breed: "Ragdoll",
        age: 3,
        sex: "Female",
        size: "Small",
        color: "Brown Mix",
        weight: 4.2,
        imageUrl: "assets/portraits/Lily.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: true,
        medicalNotes: "N/A",
        temperament: "Calm",
        houseTrained: true,
        adoptionFee: 40.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-12",
        description: "Owner passed away",
        trainingLevel: "Indoor trained",
        contactInfo: "shelter@example.com"
      },
      {
        id: 9,
        name: "Tommy",
        breed: "Red-Eared Slider",
        age: 3,
        sex: "Male",
        size: "Small",
        color: "Green & Orange",
        weight: 0.6,
        imageUrl: "assets/portraits/Tommy.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: false,
        neuteredSpayed: false,
        medicalNotes: "Needs shallow water habitat",
        temperament: "Friendly",
        houseTrained: false,
        adoptionFee: 45.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-12",
        description: "Left behind at apartment lobby",
        trainingLevel: "Basic tank acclimation",
        contactInfo: "shelter@example.com"
      },
      {
        id: 10,
        name: "Kiwi",
        breed: "Budgerigar",
        age: 1,
        sex: "Male",
        size: "Small",
        color: "Yellow & Green",
        weight: 0.05,
        imageUrl: "assets/portraits/Kiwi.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: false,
        neuteredSpayed: false,
        medicalNotes: "N/A",
        temperament: "Playful",
        houseTrained: false,
        adoptionFee: 90.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-17",
        description: "Found near subdivision park",
        trainingLevel: "Basic voice mimic",
        contactInfo: "shelter@example.com"
      },
      {
        id: 11,
        name: "Shelly",
        breed: "Red-Eared Slider",
        age: 5,
        sex: "Female",
        size: "Small",
        color: "Green & Brown",
        weight: 0.8,
        imageUrl: "assets/portraits/Shelly.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: false,
        neuteredSpayed: false,
        medicalNotes: "N/A",
        temperament: "Calm",
        houseTrained: false,
        adoptionFee: 20.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-10-25",
        description: "Left behind after moving",
        trainingLevel: "Tank trained",
        contactInfo: "shelter@example.com"
      },
      {
        id: 12,
        name: "Speedy",
        breed: "Box Turtle",
        age: 4,
        sex: "Male",
        size: "Small",
        color: "Brown",
        weight: 0.75,
        imageUrl: "assets/portraits/Speedy.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: false,
        neuteredSpayed: false,
        medicalNotes: "N/A",
        temperament: "Calm",
        houseTrained: false,
        adoptionFee: 25.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-03",
        description: "Found after flood incident",
        trainingLevel: "Basic tank acclimation",
        contactInfo: "shelter@example.com"
      },
      {
        id: 13,
        name: "Thumper",
        breed: "Netherland Dwarf",
        age: 2,
        sex: "Female",
        size: "Small",
        color: "White",
        weight: 1.1,
        imageUrl: "assets/portraits/Thumper.jpg",
        healthStatus: "Healthy",
        vaccinationStatus: "Complete",
        dewormed: true,
        neuteredSpayed: false,
        medicalNotes: "N/A",
        temperament: "Gentle",
        houseTrained: true,
        adoptionFee: 35.0,
        location: "Happy Paws Shelter, Manila",
        availabilityStatus: "Available",
        intakeDate: "2025-11-21",
        description: "Rescued from backyard cage",
        trainingLevel: "Litter box trained",
        contactInfo: "shelter@example.com"
      }
    ];
  }
}